title: One Data Cookie | DigiGarden
name: My linked notebook
user_description: onedatacookie-digigarden
notes_url: "https://onedatacookie-digigarden.netlify.app/"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: MIT
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://onedatacookie-digigarden.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
encoding: utf-8

# Author Settings
somevizes: https://onedatacookie-somevizes.netlify.app/
social-github: one-data-cookie
social-medium: one-data-cookie
social-email: kolacek.m@gmail.com
social-linkedin: kolacekm
social-twitter: kolacekm

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-toc

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: null
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge


sass:
  style: compressed

collections:
    notes:
      output: true
      permalink: /notes/:title

toc:
  max_level: 3

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
